# Site settings
name: Autonomy and Verification Laboratory
email:
author: Autonomy and Verification Laboratory

keywords: autonomous systems, robotics, artificial intelligence, formal verification, sensor systems, programming, formal modelling
description: The Autonomy and Verification Laboratory
# Only use this if you are serving your site via Github Pages
#github:

#url:  "http://localhost:4000"
#images: "http://localhost:4000/images/"

url: "https://autonomy-and-verification-uol.github.io"
images: "https://autonomy-and-verification-uol.github.io/images/"


header: no
header_sm: images/ashton-small.png
header_med: images/ashton-med.png
header_large: images/ashton-large.png
header_xl: images/ashton-xl-desat.png



# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized. ]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

# Compress our Css
#sass:
#    style: :compressed

permalink: /blog/:year/:title




#### SEO Stuff

# Twitter Cards
twitter_user: AandVNetwork
twitter_card: true
twitter_image: https://autonomy-and-verification-uol.github.io/images/ashton-home.png    #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Usernames for things
researchgate_username: Autonomy-and-Verification-Lab-Michael-Fisher

# URLS
UoL_URL: https://www.liverpool.ac.uk/computer-science/
UoY_URL: https://www.cs.york.ac.uk/
AA_URL: https://www.york.ac.uk/assuring-autonomy/
ONR_URL: http://www.onr.org.uk/
NCNR_HUB_URL: https://www.ncnr.org.uk/
RAIN_HUB_URL: https://rainhub.org.uk/
VV_NETWORK_URL: https://vavas.org/
